FROM tiangolo/uwsgi-nginx-flask:python2.7
RUN mkdir /home/dockeruser
RUN chmod 777 /home/dockeruser
ENV HOME=/home/dockeruser

RUN apt-get update && apt-get install -y vim

#see explanation in Dockerfile-nest_ops
RUN pip install setuptools==33.1.1

#postgres/python interop for sqlalchemy
RUN apt-get update && apt-get install -y libpq-dev python-dev

# install python libs
ADD ./requirements /code_buildtime_tmp/requirements
WORKDIR /code_buildtime_tmp
RUN pip install -q -r requirements/nest_flask.txt

# remove the sample app
RUN rm -rf /app

# skip the ENTRYPOINT defined in the base image, which clobbers much of our config
ENTRYPOINT ["/code_live/docker/flask_entrypoint.sh"]
